### ISSUE TITLE
About database setup

### ISSUE THREAD

**Issue by karllaurence** [zaggash/docker-filerun#2]
Hi,

I have tried your docker image on Debian 8 with official nginx docker and it could display the setup webpage in the browser. When I try to setup the database during the installation step, I have some problems. When I set MySQL Hostname as normal, localhost, it displays MySQL: SQLSTATE[HY000] [2002] No such file or directory. When I set it as 127.0.0.1 or others, it says MySQL: SQLSTATE[HY000] [2002] Connection refused. When I set is as localhost:80 or 127.0.0.1:80, it displays the pop windows setting up for very long time and seems nothing was done. May I get some help from you? I could provide with more details if needed. Thank you very much!

**Comment by zaggash** [comment]
Hi,

Its been a while since I used FileRun.
I though we were able to use sqlite...

Otherwise, since you are inside a container, you have to run a mysql next to Filerun.
Do you already have a mysql DB ?
You cannot use 127.0.0.1 or localhost because this will refer to the FileRun container and there isn't a MySQL DB running.
I can share a docker-compose to setup the full stack :
Filerun and a Mysql.

**Comment by karllaurence** [comment]
Thanks for your prompt reply! In fact, I have tried to create a MariaDB container and then use `--link mariadbxxxxxx:mariadb` to link to the MariaDB container. I use `mariadb` in the MySQL localhost part and then it keeps displayed `Setting up database...`. When I look at the inspect view of the webpage, there are two errors: one is `Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)` of the url https://url/?module=install&page=mysql_setup and another is `ReferenceError: Can't find variable: resp`. May I get some help from you? Or as you said a docker-compose .yml file to setup filerun and MySQL/MariaDB is welcomed!

Or I will be more than happy if you provide me with some information of using SQLite as the database as I get stuck at the Database setup step. Thanks very much!

**Comment by zaggash** [comment]
I hear you.
I'll take a look asap.
I'll let you know when I found an answer.

**Comment by zaggash** [comment]
Here is a docker-compose to make Filerun works properly.
Edit the `MYSQL_DATABASE`, `MYSQL_USER` and `MYSQL_PASSWORD` accordingly in the compose file.

In the Filerun setup webui, use `filerun_db_svc` instead of `localhost` and fill in the `MYSQL_DATABASE`, `MYSQL_USER` and `MYSQL_PASSWORD`

```
version: '3.1'

networks:
  filerun_network:

services:
  filerun_webui_svc:
    image: zaggash/docker-filerun:latest
    logging:
       driver: json-file
       options:
         max-size: "10m"
         max-file: "3"
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./filerun_webui_vol:/config
    ports:
      - "8080:80"
    networks:
      - filerun_network
    depends_on:
      - filerun_db_svc
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:80 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3


  filerun_db_svc:
    image: mariadb:10.3.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      #MYSQL_ROOT_PASSWORD: "mysql_root_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "filerun_db"
      MYSQL_USER: "filerun_user"
      MYSQL_PASSWORD: "filerun_password"
    volumes:
       - ./filerun_db_vol:/var/lib/mysql
    networks:
       - filerun_network
    healthcheck:
      test: ["CMD-SHELL", "mysql -hlocalhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD -D$$MYSQL_DATABASE -e 'show tables;' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
```
